/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedSellerRouteImport } from './routes/_authed/seller'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedUserDataRouteImport } from './routes/_authed/user/data'
import { Route as AuthedSellerProdukRouteImport } from './routes/_authed/seller/produk'
import { Route as AuthedSellerPesananRouteImport } from './routes/_authed/seller/pesanan'
import { Route as AuthedSellerDashboardRouteImport } from './routes/_authed/seller/dashboard'
import { Route as AuthedSellerCustomerRouteImport } from './routes/_authed/seller/customer'
import { Route as AuthedSellerChatRouteImport } from './routes/_authed/seller/chat'
import { Route as AuthedAdminTokoRouteImport } from './routes/_authed/admin/toko'
import { Route as AuthedAdminPesananRouteImport } from './routes/_authed/admin/pesanan'
import { Route as AuthedAdminKategoriRouteImport } from './routes/_authed/admin/kategori'
import { Route as AuthedAdminDashboard2RouteImport } from './routes/_authed/admin/dashboard2'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'
import { Route as AuthedAdminCustomerRouteImport } from './routes/_authed/admin/customer'
import { Route as AuthedAdminApprovalRouteImport } from './routes/_authed/admin/approval'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSellerRoute = AuthedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUserDataRoute = AuthedUserDataRouteImport.update({
  id: '/user/data',
  path: '/user/data',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSellerProdukRoute = AuthedSellerProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AuthedSellerRoute,
} as any)
const AuthedSellerPesananRoute = AuthedSellerPesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => AuthedSellerRoute,
} as any)
const AuthedSellerDashboardRoute = AuthedSellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedSellerRoute,
} as any)
const AuthedSellerCustomerRoute = AuthedSellerCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthedSellerRoute,
} as any)
const AuthedSellerChatRoute = AuthedSellerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedSellerRoute,
} as any)
const AuthedAdminTokoRoute = AuthedAdminTokoRouteImport.update({
  id: '/toko',
  path: '/toko',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminPesananRoute = AuthedAdminPesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminKategoriRoute = AuthedAdminKategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDashboard2Route = AuthedAdminDashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminCustomerRoute = AuthedAdminCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminApprovalRoute = AuthedAdminApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/seller': typeof AuthedSellerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/approval': typeof AuthedAdminApprovalRoute
  '/admin/customer': typeof AuthedAdminCustomerRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/dashboard2': typeof AuthedAdminDashboard2Route
  '/admin/kategori': typeof AuthedAdminKategoriRoute
  '/admin/pesanan': typeof AuthedAdminPesananRoute
  '/admin/toko': typeof AuthedAdminTokoRoute
  '/seller/chat': typeof AuthedSellerChatRoute
  '/seller/customer': typeof AuthedSellerCustomerRoute
  '/seller/dashboard': typeof AuthedSellerDashboardRoute
  '/seller/pesanan': typeof AuthedSellerPesananRoute
  '/seller/produk': typeof AuthedSellerProdukRoute
  '/user/data': typeof AuthedUserDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/seller': typeof AuthedSellerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/approval': typeof AuthedAdminApprovalRoute
  '/admin/customer': typeof AuthedAdminCustomerRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/dashboard2': typeof AuthedAdminDashboard2Route
  '/admin/kategori': typeof AuthedAdminKategoriRoute
  '/admin/pesanan': typeof AuthedAdminPesananRoute
  '/admin/toko': typeof AuthedAdminTokoRoute
  '/seller/chat': typeof AuthedSellerChatRoute
  '/seller/customer': typeof AuthedSellerCustomerRoute
  '/seller/dashboard': typeof AuthedSellerDashboardRoute
  '/seller/pesanan': typeof AuthedSellerPesananRoute
  '/seller/produk': typeof AuthedSellerProdukRoute
  '/user/data': typeof AuthedUserDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/seller': typeof AuthedSellerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authed/admin/approval': typeof AuthedAdminApprovalRoute
  '/_authed/admin/customer': typeof AuthedAdminCustomerRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/admin/dashboard2': typeof AuthedAdminDashboard2Route
  '/_authed/admin/kategori': typeof AuthedAdminKategoriRoute
  '/_authed/admin/pesanan': typeof AuthedAdminPesananRoute
  '/_authed/admin/toko': typeof AuthedAdminTokoRoute
  '/_authed/seller/chat': typeof AuthedSellerChatRoute
  '/_authed/seller/customer': typeof AuthedSellerCustomerRoute
  '/_authed/seller/dashboard': typeof AuthedSellerDashboardRoute
  '/_authed/seller/pesanan': typeof AuthedSellerPesananRoute
  '/_authed/seller/produk': typeof AuthedSellerProdukRoute
  '/_authed/user/data': typeof AuthedUserDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/admin'
    | '/seller'
    | '/auth/login'
    | '/auth/register'
    | '/demo/tanstack-query'
    | '/admin/approval'
    | '/admin/customer'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/admin/kategori'
    | '/admin/pesanan'
    | '/admin/toko'
    | '/seller/chat'
    | '/seller/customer'
    | '/seller/dashboard'
    | '/seller/pesanan'
    | '/seller/produk'
    | '/user/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/admin'
    | '/seller'
    | '/auth/login'
    | '/auth/register'
    | '/demo/tanstack-query'
    | '/admin/approval'
    | '/admin/customer'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/admin/kategori'
    | '/admin/pesanan'
    | '/admin/toko'
    | '/seller/chat'
    | '/seller/customer'
    | '/seller/dashboard'
    | '/seller/pesanan'
    | '/seller/produk'
    | '/user/data'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/home'
    | '/_authed/admin'
    | '/_authed/seller'
    | '/auth/login'
    | '/auth/register'
    | '/demo/tanstack-query'
    | '/_authed/admin/approval'
    | '/_authed/admin/customer'
    | '/_authed/admin/dashboard'
    | '/_authed/admin/dashboard2'
    | '/_authed/admin/kategori'
    | '/_authed/admin/pesanan'
    | '/_authed/admin/toko'
    | '/_authed/seller/chat'
    | '/_authed/seller/customer'
    | '/_authed/seller/dashboard'
    | '/_authed/seller/pesanan'
    | '/_authed/seller/produk'
    | '/_authed/user/data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/seller': {
      id: '/_authed/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthedSellerRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/user/data': {
      id: '/_authed/user/data'
      path: '/user/data'
      fullPath: '/user/data'
      preLoaderRoute: typeof AuthedUserDataRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/seller/produk': {
      id: '/_authed/seller/produk'
      path: '/produk'
      fullPath: '/seller/produk'
      preLoaderRoute: typeof AuthedSellerProdukRouteImport
      parentRoute: typeof AuthedSellerRoute
    }
    '/_authed/seller/pesanan': {
      id: '/_authed/seller/pesanan'
      path: '/pesanan'
      fullPath: '/seller/pesanan'
      preLoaderRoute: typeof AuthedSellerPesananRouteImport
      parentRoute: typeof AuthedSellerRoute
    }
    '/_authed/seller/dashboard': {
      id: '/_authed/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof AuthedSellerDashboardRouteImport
      parentRoute: typeof AuthedSellerRoute
    }
    '/_authed/seller/customer': {
      id: '/_authed/seller/customer'
      path: '/customer'
      fullPath: '/seller/customer'
      preLoaderRoute: typeof AuthedSellerCustomerRouteImport
      parentRoute: typeof AuthedSellerRoute
    }
    '/_authed/seller/chat': {
      id: '/_authed/seller/chat'
      path: '/chat'
      fullPath: '/seller/chat'
      preLoaderRoute: typeof AuthedSellerChatRouteImport
      parentRoute: typeof AuthedSellerRoute
    }
    '/_authed/admin/toko': {
      id: '/_authed/admin/toko'
      path: '/toko'
      fullPath: '/admin/toko'
      preLoaderRoute: typeof AuthedAdminTokoRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/pesanan': {
      id: '/_authed/admin/pesanan'
      path: '/pesanan'
      fullPath: '/admin/pesanan'
      preLoaderRoute: typeof AuthedAdminPesananRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/kategori': {
      id: '/_authed/admin/kategori'
      path: '/kategori'
      fullPath: '/admin/kategori'
      preLoaderRoute: typeof AuthedAdminKategoriRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/dashboard2': {
      id: '/_authed/admin/dashboard2'
      path: '/dashboard2'
      fullPath: '/admin/dashboard2'
      preLoaderRoute: typeof AuthedAdminDashboard2RouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/customer': {
      id: '/_authed/admin/customer'
      path: '/customer'
      fullPath: '/admin/customer'
      preLoaderRoute: typeof AuthedAdminCustomerRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/approval': {
      id: '/_authed/admin/approval'
      path: '/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AuthedAdminApprovalRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminApprovalRoute: typeof AuthedAdminApprovalRoute
  AuthedAdminCustomerRoute: typeof AuthedAdminCustomerRoute
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminDashboard2Route: typeof AuthedAdminDashboard2Route
  AuthedAdminKategoriRoute: typeof AuthedAdminKategoriRoute
  AuthedAdminPesananRoute: typeof AuthedAdminPesananRoute
  AuthedAdminTokoRoute: typeof AuthedAdminTokoRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminApprovalRoute: AuthedAdminApprovalRoute,
  AuthedAdminCustomerRoute: AuthedAdminCustomerRoute,
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminDashboard2Route: AuthedAdminDashboard2Route,
  AuthedAdminKategoriRoute: AuthedAdminKategoriRoute,
  AuthedAdminPesananRoute: AuthedAdminPesananRoute,
  AuthedAdminTokoRoute: AuthedAdminTokoRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedSellerRouteChildren {
  AuthedSellerChatRoute: typeof AuthedSellerChatRoute
  AuthedSellerCustomerRoute: typeof AuthedSellerCustomerRoute
  AuthedSellerDashboardRoute: typeof AuthedSellerDashboardRoute
  AuthedSellerPesananRoute: typeof AuthedSellerPesananRoute
  AuthedSellerProdukRoute: typeof AuthedSellerProdukRoute
}

const AuthedSellerRouteChildren: AuthedSellerRouteChildren = {
  AuthedSellerChatRoute: AuthedSellerChatRoute,
  AuthedSellerCustomerRoute: AuthedSellerCustomerRoute,
  AuthedSellerDashboardRoute: AuthedSellerDashboardRoute,
  AuthedSellerPesananRoute: AuthedSellerPesananRoute,
  AuthedSellerProdukRoute: AuthedSellerProdukRoute,
}

const AuthedSellerRouteWithChildren = AuthedSellerRoute._addFileChildren(
  AuthedSellerRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedSellerRoute: typeof AuthedSellerRouteWithChildren
  AuthedUserDataRoute: typeof AuthedUserDataRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedSellerRoute: AuthedSellerRouteWithChildren,
  AuthedUserDataRoute: AuthedUserDataRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
