FROM golang:1.24-alpine
RUN apk add --no-cache ca-certificates

WORKDIR /app

# install air untuk hot reload
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8081

CMD ["go", "run", "./cmd/api"]
