import 'package:flutter/material.dart';
import 'package:app/core/models/category_model.dart';
import 'package:app/core/models/product_model.dart';

final List<CategoryModel> dummyCategories = [
  const CategoryModel(
    id: 'cat-1',
    name: 'All',
    slug: 'all',
    icon: Icons.apps_rounded,
  ),
  const CategoryModel(
    id: 'cat-2',
    name: 'Organic',
    slug: 'organic',
    icon: Icons.eco_rounded,
  ),
  const CategoryModel(
    id: 'cat-3',
    name: 'Skincare',
    slug: 'skincare',
    icon: Icons.face_retouching_natural,
  ),
  const CategoryModel(
    id: 'cat-4',
    name: 'Fashion',
    slug: 'fashion',
    icon: Icons.checkroom_rounded,
  ),
  const CategoryModel(
    id: 'cat-5',
    name: 'Home',
    slug: 'home',
    icon: Icons.home_rounded,
  ),
  const CategoryModel(
    id: 'cat-6',
    name: 'Food',
    slug: 'food',
    icon: Icons.restaurant_rounded,
  ),
  const CategoryModel(
    id: 'cat-7',
    name: 'Drinks',
    slug: 'drinks',
    icon: Icons.local_cafe_rounded,
  ),
];

final List<ProductModel> dummyProducts = [
  ProductModel(
    id: 'prod-1',
    shopId: 'shop-1',
    categoryId: 'cat-2',
    name: 'Bamboo Toothbrush Set',
    slug: 'bamboo-toothbrush-set',
    description:
        'Eco-friendly bamboo toothbrush set, biodegradable and sustainable.',
    sku: 'BTB-001',
    favoriteCount: 320,
    reviewCount: 87,
    ratingAverage: 4.8,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400',
    price: const ProductPrice(amount: 45000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 200, reservedStock: 12),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.2,
      recyclable: true,
      materialType: 'Bamboo',
      ecoScore: 9.2,
    ),
    discount: const ProductDiscount(
      name: 'Flash Sale',
      percentage: 20,
      isActive: true,
    ),
  ),
  ProductModel(
    id: 'prod-2',
    shopId: 'shop-1',
    categoryId: 'cat-3',
    name: 'Aloe Vera Moisturizer',
    slug: 'aloe-vera-moisturizer',
    description: 'Natural aloe vera moisturizer with zero chemicals.',
    sku: 'AVM-002',
    favoriteCount: 512,
    reviewCount: 143,
    ratingAverage: 4.6,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
    price: const ProductPrice(amount: 125000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 80, reservedStock: 5),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.5,
      recyclable: true,
      materialType: 'Plant-based',
      ecoScore: 8.7,
    ),
  ),
  ProductModel(
    id: 'prod-3',
    shopId: 'shop-2',
    categoryId: 'cat-4',
    name: 'Organic Cotton Tote Bag',
    slug: 'organic-cotton-tote',
    description: 'Reusable tote bag made from 100% organic cotton.',
    sku: 'OCT-003',
    favoriteCount: 890,
    reviewCount: 210,
    ratingAverage: 4.9,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
    price: const ProductPrice(amount: 85000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 500, reservedStock: 45),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.1,
      recyclable: true,
      materialType: 'Organic Cotton',
      ecoScore: 9.8,
    ),
    discount: const ProductDiscount(
      name: 'Weekend Deal',
      percentage: 15,
      isActive: true,
    ),
  ),
  ProductModel(
    id: 'prod-4',
    shopId: 'shop-2',
    categoryId: 'cat-6',
    name: 'Cold Brew Coffee Blend',
    slug: 'cold-brew-coffee-blend',
    description: 'Single-origin arabica beans, ethically sourced.',
    sku: 'CBC-004',
    favoriteCount: 234,
    reviewCount: 65,
    ratingAverage: 4.7,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    price: const ProductPrice(amount: 95000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 150, reservedStock: 20),
  ),
  ProductModel(
    id: 'prod-5',
    shopId: 'shop-3',
    categoryId: 'cat-5',
    name: 'Beeswax Candle Set',
    slug: 'beeswax-candle-set',
    description: 'Handcrafted beeswax candles with natural scents.',
    sku: 'BWC-005',
    favoriteCount: 445,
    reviewCount: 98,
    ratingAverage: 4.5,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1602607507577-b48dad5e9f27?w=400',
    price: const ProductPrice(amount: 75000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 60, reservedStock: 8),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.3,
      recyclable: false,
      materialType: 'Beeswax',
      ecoScore: 8.1,
    ),
  ),
  ProductModel(
    id: 'prod-6',
    shopId: 'shop-3',
    categoryId: 'cat-7',
    name: 'Herbal Kombucha Pack',
    slug: 'herbal-kombucha-pack',
    description: 'Probiotic-rich kombucha brewed with organic herbs.',
    sku: 'HKP-006',
    favoriteCount: 671,
    reviewCount: 177,
    ratingAverage: 4.4,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400',
    price: const ProductPrice(amount: 55000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 120, reservedStock: 15),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.4,
      recyclable: true,
      materialType: 'Glass Bottle',
      ecoScore: 8.5,
    ),
    discount: const ProductDiscount(
      name: 'New Arrival',
      percentage: 10,
      isActive: true,
    ),
  ),
  ProductModel(
    id: 'prod-7',
    shopId: 'shop-1',
    categoryId: 'cat-3',
    name: 'Charcoal Face Wash',
    slug: 'charcoal-face-wash',
    description: 'Deep cleansing charcoal face wash with natural extracts.',
    sku: 'CFW-007',
    favoriteCount: 388,
    reviewCount: 102,
    ratingAverage: 4.3,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400',
    price: const ProductPrice(amount: 68000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 90, reservedStock: 10),
  ),
  ProductModel(
    id: 'prod-8',
    shopId: 'shop-2',
    categoryId: 'cat-2',
    name: 'Reusable Produce Bags',
    slug: 'reusable-produce-bags',
    description: 'Set of 6 mesh produce bags to replace plastic.',
    sku: 'RPB-008',
    favoriteCount: 562,
    reviewCount: 134,
    ratingAverage: 4.8,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    price: const ProductPrice(amount: 38000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 300, reservedStock: 22),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.05,
      recyclable: true,
      materialType: 'Recycled Mesh',
      ecoScore: 9.9,
    ),
    discount: const ProductDiscount(
      name: 'Eco Bundle',
      percentage: 25,
      isActive: true,
    ),
  ),
  ProductModel(
    id: 'prod-9',
    shopId: 'shop-3',
    categoryId: 'cat-5',
    name: 'Hemp Rope Basket',
    slug: 'hemp-rope-basket',
    description: 'Handwoven storage basket made from natural hemp rope.',
    sku: 'HRB-009',
    favoriteCount: 219,
    reviewCount: 58,
    ratingAverage: 4.6,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1595348020949-87cdfbb44174?w=400',
    price: const ProductPrice(amount: 115000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 40, reservedStock: 3),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.2,
      recyclable: true,
      materialType: 'Hemp',
      ecoScore: 9.4,
    ),
  ),
  ProductModel(
    id: 'prod-10',
    shopId: 'shop-1',
    categoryId: 'cat-6',
    name: 'Organic Granola Jar',
    slug: 'organic-granola-jar',
    description: 'Crunchy granola made with organic oats, honey, and nuts.',
    sku: 'OGJ-010',
    favoriteCount: 793,
    reviewCount: 256,
    ratingAverage: 4.9,
    isActive: true,
    imageUrl:
        'https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=400',
    price: const ProductPrice(amount: 72000, currency: 'IDR'),
    inventory: const ProductInventory(stock: 175, reservedStock: 30),
    ecoAttribute: const EcoAttribute(
      carbonFootprint: 0.6,
      recyclable: true,
      materialType: 'Organic',
      ecoScore: 8.8,
    ),
    discount: const ProductDiscount(
      name: 'Best Seller',
      percentage: 5,
      isActive: true,
    ),
  ),
];
