FROM node:20-alpine

WORKDIR /app

RUN corepack enable

# 🔥 PENTING: paksa development mode
ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./

# 🔥 pastikan devDependencies ke-install
RUN pnpm install --shamefully-hoist --prod=false

COPY . .

# 🔥 install ulang karena pakai volume + sync
CMD ["sh", "-c", "pnpm install --shamefully-hoist --prod=false && pnpm run start:dev"]