FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

ENV NODE_ENV=development

RUN pnpm install --prod=false

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]