FROM node:22

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@10.12.4 --activate

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --shamefully-hoist --prod=false

COPY . .

CMD ["pnpm", "run", "start"]
